### ISSUE TITLE
Use Pixy to identify "control panel" rotation and current color

### ISSUE THREAD

**Issue by dandeduck** [Flash3388/Flash2020#1]
Part of the game objectives include identifying rotation of the "Control Panel". We wish to do so using Pixy. Using either Pixy 1 or 2, see if it is possible to identify a full rotation, and the current color. Do so on some personal computer, no need for roboRIO yet.

This includes writing code which reads the results.

**Comment by TheCH150503** [comment]
1) install cmake
2) install MinGW
3) download pixy Git Rep - https://github.com/charmedlabs/pixy
4) compile libpixyusb (search compile cmake with MinGW)
5) create an example with uses pixy (Use "Hello Pixy" program for reference)
6) create a code for the Control Panel (The Color Wheel)
