### ISSUE TITLE
Design how to position robot under generator switch according to other robot's weight and position

### ISSUE THREAD

**Issue by yaronkle** [Flash3388/Flash2020#12]
At the end of the match, the driver needs to reposition the robot under the generator switch pole.
The Robot needs to be able to position itself in the correct position of the pole so that it will be level with the other robot.

We need to come up with designs / ideas for positioning the robot at the right place.
For example, we might our robot to position itself in the correct location under the pole so that the generator switch will be level.
For that we will need to know the other robot's weight and position.

Once we have a good design we might need to purchase and put on the robot additional equipment ultrasonic sensors.

**Comment by dandeduck** [comment]
kinda hard to do... Even with a lot of ultrasonics in many directions won't really help because of their inaccuracy while at an angle
