### ISSUE TITLE
Test and update interpolation methods

### ISSUE THREAD

**Issue by dandeduck** [Flash3388/Flash2020#15]
for angle and/or speed adjustments according to distance in this year's robot

**Comment by tomtzook** [comment]
From `jmath`:
```Java
Map<Double, Double> points = .....
Interpolation interpolation = LagrangePolynomial.fromMap(points);
double yForGivenX = interpolation.applyAsDouble(someXToFindYFor);
```

**Comment by tomtzook** [comment]
Forgot to mention that first we must determine the type of function we wish to interpolate. We may need to provide a new implementation in that case.

[For rational interpolation](https://www.alglib.net/interpolation/rational.php)
[Also read](http://folk.uio.no/chrischu/research/papers/Schulz_PhDThesis.pdf)

**Comment by tomtzook** [comment]
From `jmath:1.1.0`:
```Java
Map<Double, Double> points = .....
Interpolation interpolation = BarycentricRational.fromMap(points, accuracyMeasureD);
double yForGivenX = interpolation.applyAsDouble(someXToFindYFor);
```
Parameters must be tested to find the best working ones. Including amount of points, range, and _d_.
