### ISSUE TITLE
Pixy integration with RoboRIO

### ISSUE THREAD

**Issue by dandeduck** [Flash3388/Flash2020#2]
Connect and interface Pixy with RoboRIO. Check API integration and test control and data. This may involve a need for JNI.

**Comment by tomtzook** [comment]
We can use [jpixy](https://github.com/tomtzook/jpixy), which is a java port for `libpixyusb`. We would first need to compile and install the libraries like any other linux. Then, simply connect it via USB to the _roborio_ and voila.

**Comment by dandeduck** [comment]
need to get Guy working on it

**Comment by tomtzook** [comment]
> need to get Guy working on it

On using `jpixy`
