### ISSUE TITLE
Turret System

### ISSUE THREAD

**Issue by tomtzook** [Flash3388/Flash2020#20]
1x Motor for rotating the turret.
1x Gyroscope for turret bearing.

**Comment by tomtzook** [comment]
For Tamir

**Comment by tomtzook** [comment]
Code is mostly complete. Awaiting tests.

**Comment by dandeduck** [comment]
Need to add PID and vision based system to rotate the turret, kinda like what we did last year with the hatch alignment

**Comment by tomtzook** [comment]
vision-based?
