### ISSUE TITLE
Create an autonomous picking system

### ISSUE THREAD

**Issue by dandeduck** [Flash3388/Flash2020#26]
We have a lot of autonomous options this year, so we need to create a system for easily picking them without additional code uploads. It will most likely consist out of a number of sliders like "position" (left, centre, and middle) then options like (collect - shoot or shoot-collect or shoot - drive or wait-shoot-drive etc.) probably using shuffleboard

**Comment by tomtzook** [comment]
The combo-box from the dashboard.... [`SendableChooser`](https://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.html)

**Comment by dandeduck** [comment]
yeah, but I am talking about a combination of a number of them

**Comment by dandeduck** [comment]
also talking about the autonomous dataset
