### ISSUE TITLE
FlashLib 2020

### ISSUE THREAD

**Issue by dandeduck** [Flash3388/Flash2020#9]
Test integration with new WPILib version.

**Comment by tomtzook** [comment]
Test:
  - IterativeFrcRobot
  - TimedFrcRobot
  - FpgaClock
  - FrcHidInterface (XboxController, Joystick)
  - SpeedContollers (TalonSRX)       
  - Robot base delay reporting

**Comment by tomtzook** [comment]
Create automated tests eventually

**Comment by tomtzook** [comment]
Done. Ran several tests, fixed some stuff. Releasing new versions.
